import './sidebar.css'

export default function sidebar () {
    return (
        <div className='Sidebar'>
            <div className="sidebarItem">
                <span className='sidebarTitle'>ABOUT ME</span>
            </div>
            <div className='sidebarItem'>
                <p>
                    TKSP is a website where people go to find information.
                    Every piece of content on this site is generated by users,
                    which allows user to create social networks and follow topics that
                    interest them.
                </p>
            </div>
            <div className="sidebarItem">
                <span className='sidebarTitle'>CATEGORIES</span>
            </div>
            <div className="sidebarItem">
                <ul className="sidebarList">
                    <li className="sidebarListItem">Technology</li>
                    <li className="sidebarListItem">Food</li>
                    <li className="sidebarListItem">Music</li>
                    <li className="sidebarListItem">Business</li>
                    <li className="sidebarListItem">Movies & TV</li>
                    <li className="sidebarListItem">Sport</li>
                </ul>
            </div>
        </div>
    )
}
